### ISSUE TITLE
Use session data manager

### ISSUE THREAD

**Issue by puittenbroek** [collective/collective.smsauthenticator#14]
At the moment we're using signed url's and passing those around.
In Plone/Zope, there's a session data manager which we can use to store some information.
This works by making a cookie with the session id.

More info:
http://docs.plone.org/4/en/develop/plone/sessions/session_variables.html

**Comment by djay** [comment]
sessions in plone has issues. If you do load balancing then you have to do special things to ensure sessions are replicated between instances since they aren't by default. or do sticky loadbalancing. This is normally not needed because plone itself, and most plugins don't use sessions. If you can avoid sessions, it makes others lives easier.

**Comment by barseghyanartur** [comment]
@puittenbroek:

It looks like we're doing fine by using signed URLs. Close?

**Comment by puittenbroek** [comment]
@barseghyanartur Seeing @djay comment I'm inclined to agree :)

Thanks @djay! This also explains another issue I had with session in other project..
